package Enums;

public enum TipoSubCategoria {

    DISCO_EXTERNO, DISCO_RIGIDO, DISCO_SOLIDO_SSD, CERTIFICADA, GENERICA, MEMORIA_RAM, MEMORIA_NOTEBOOK, PLACA_DE_VIDEO_GEFORCE, PLACA_DE_VIDEO_RADEONAMD,
    PLACA_INTEL, PLACA_AMD, PROCESADOR_AMD, PROCESADOR_INTEL, COOLER_CPU, COOLER_FAN, PLACA_DE_RED, NINGUNA;
}
